/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZeitplanIndexRouteImport } from './routes/zeitplan/index'
import { Route as TeamIndexRouteImport } from './routes/team/index'
import { Route as PresseIndexRouteImport } from './routes/presse/index'
import { Route as PartnerIndexRouteImport } from './routes/partner/index'
import { Route as KonzeptIndexRouteImport } from './routes/konzept/index'
import { Route as KontaktIndexRouteImport } from './routes/kontakt/index'
import { Route as ImpressumIndexRouteImport } from './routes/impressum/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as TeamVornameRouteImport } from './routes/team/$vorname'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZeitplanIndexRoute = ZeitplanIndexRouteImport.update({
  id: '/zeitplan/',
  path: '/zeitplan/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIndexRoute = TeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => rootRouteImport,
} as any)
const PresseIndexRoute = PresseIndexRouteImport.update({
  id: '/presse/',
  path: '/presse/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerIndexRoute = PartnerIndexRouteImport.update({
  id: '/partner/',
  path: '/partner/',
  getParentRoute: () => rootRouteImport,
} as any)
const KonzeptIndexRoute = KonzeptIndexRouteImport.update({
  id: '/konzept/',
  path: '/konzept/',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktIndexRoute = KontaktIndexRouteImport.update({
  id: '/kontakt/',
  path: '/kontakt/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumIndexRoute = ImpressumIndexRouteImport.update({
  id: '/impressum/',
  path: '/impressum/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamVornameRoute = TeamVornameRouteImport.update({
  id: '/team/$vorname',
  path: '/team/$vorname',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/team/$vorname': typeof TeamVornameRoute
  '/blog/': typeof BlogIndexRoute
  '/impressum/': typeof ImpressumIndexRoute
  '/kontakt/': typeof KontaktIndexRoute
  '/konzept/': typeof KonzeptIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/presse/': typeof PresseIndexRoute
  '/team/': typeof TeamIndexRoute
  '/zeitplan/': typeof ZeitplanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/team/$vorname': typeof TeamVornameRoute
  '/blog': typeof BlogIndexRoute
  '/impressum': typeof ImpressumIndexRoute
  '/kontakt': typeof KontaktIndexRoute
  '/konzept': typeof KonzeptIndexRoute
  '/partner': typeof PartnerIndexRoute
  '/presse': typeof PresseIndexRoute
  '/team': typeof TeamIndexRoute
  '/zeitplan': typeof ZeitplanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/team/$vorname': typeof TeamVornameRoute
  '/blog/': typeof BlogIndexRoute
  '/impressum/': typeof ImpressumIndexRoute
  '/kontakt/': typeof KontaktIndexRoute
  '/konzept/': typeof KonzeptIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/presse/': typeof PresseIndexRoute
  '/team/': typeof TeamIndexRoute
  '/zeitplan/': typeof ZeitplanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog/$slug'
    | '/team/$vorname'
    | '/blog/'
    | '/impressum/'
    | '/kontakt/'
    | '/konzept/'
    | '/partner/'
    | '/presse/'
    | '/team/'
    | '/zeitplan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog/$slug'
    | '/team/$vorname'
    | '/blog'
    | '/impressum'
    | '/kontakt'
    | '/konzept'
    | '/partner'
    | '/presse'
    | '/team'
    | '/zeitplan'
  id:
    | '__root__'
    | '/'
    | '/blog/$slug'
    | '/team/$vorname'
    | '/blog/'
    | '/impressum/'
    | '/kontakt/'
    | '/konzept/'
    | '/partner/'
    | '/presse/'
    | '/team/'
    | '/zeitplan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogSlugRoute: typeof BlogSlugRoute
  TeamVornameRoute: typeof TeamVornameRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ImpressumIndexRoute: typeof ImpressumIndexRoute
  KontaktIndexRoute: typeof KontaktIndexRoute
  KonzeptIndexRoute: typeof KonzeptIndexRoute
  PartnerIndexRoute: typeof PartnerIndexRoute
  PresseIndexRoute: typeof PresseIndexRoute
  TeamIndexRoute: typeof TeamIndexRoute
  ZeitplanIndexRoute: typeof ZeitplanIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zeitplan/': {
      id: '/zeitplan/'
      path: '/zeitplan'
      fullPath: '/zeitplan/'
      preLoaderRoute: typeof ZeitplanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/': {
      id: '/team/'
      path: '/team'
      fullPath: '/team/'
      preLoaderRoute: typeof TeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presse/': {
      id: '/presse/'
      path: '/presse'
      fullPath: '/presse/'
      preLoaderRoute: typeof PresseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/': {
      id: '/partner/'
      path: '/partner'
      fullPath: '/partner/'
      preLoaderRoute: typeof PartnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konzept/': {
      id: '/konzept/'
      path: '/konzept'
      fullPath: '/konzept/'
      preLoaderRoute: typeof KonzeptIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt/': {
      id: '/kontakt/'
      path: '/kontakt'
      fullPath: '/kontakt/'
      preLoaderRoute: typeof KontaktIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum/': {
      id: '/impressum/'
      path: '/impressum'
      fullPath: '/impressum/'
      preLoaderRoute: typeof ImpressumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$vorname': {
      id: '/team/$vorname'
      path: '/team/$vorname'
      fullPath: '/team/$vorname'
      preLoaderRoute: typeof TeamVornameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogSlugRoute: BlogSlugRoute,
  TeamVornameRoute: TeamVornameRoute,
  BlogIndexRoute: BlogIndexRoute,
  ImpressumIndexRoute: ImpressumIndexRoute,
  KontaktIndexRoute: KontaktIndexRoute,
  KonzeptIndexRoute: KonzeptIndexRoute,
  PartnerIndexRoute: PartnerIndexRoute,
  PresseIndexRoute: PresseIndexRoute,
  TeamIndexRoute: TeamIndexRoute,
  ZeitplanIndexRoute: ZeitplanIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
