/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TraegerIndexRouteImport } from './routes/traeger/index'
import { Route as TeamIndexRouteImport } from './routes/team/index'
import { Route as KonzeptIndexRouteImport } from './routes/konzept/index'
import { Route as ImpressumIndexRouteImport } from './routes/impressum/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as TeamVornameRouteImport } from './routes/team/$vorname'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TraegerIndexRoute = TraegerIndexRouteImport.update({
  id: '/traeger/',
  path: '/traeger/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIndexRoute = TeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => rootRouteImport,
} as any)
const KonzeptIndexRoute = KonzeptIndexRouteImport.update({
  id: '/konzept/',
  path: '/konzept/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumIndexRoute = ImpressumIndexRouteImport.update({
  id: '/impressum/',
  path: '/impressum/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamVornameRoute = TeamVornameRouteImport.update({
  id: '/team/$vorname',
  path: '/team/$vorname',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/team/$vorname': typeof TeamVornameRoute
  '/blog/': typeof BlogIndexRoute
  '/impressum/': typeof ImpressumIndexRoute
  '/konzept/': typeof KonzeptIndexRoute
  '/team/': typeof TeamIndexRoute
  '/traeger/': typeof TraegerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/team/$vorname': typeof TeamVornameRoute
  '/blog': typeof BlogIndexRoute
  '/impressum': typeof ImpressumIndexRoute
  '/konzept': typeof KonzeptIndexRoute
  '/team': typeof TeamIndexRoute
  '/traeger': typeof TraegerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/team/$vorname': typeof TeamVornameRoute
  '/blog/': typeof BlogIndexRoute
  '/impressum/': typeof ImpressumIndexRoute
  '/konzept/': typeof KonzeptIndexRoute
  '/team/': typeof TeamIndexRoute
  '/traeger/': typeof TraegerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog/$slug'
    | '/team/$vorname'
    | '/blog/'
    | '/impressum/'
    | '/konzept/'
    | '/team/'
    | '/traeger/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog/$slug'
    | '/team/$vorname'
    | '/blog'
    | '/impressum'
    | '/konzept'
    | '/team'
    | '/traeger'
  id:
    | '__root__'
    | '/'
    | '/blog/$slug'
    | '/team/$vorname'
    | '/blog/'
    | '/impressum/'
    | '/konzept/'
    | '/team/'
    | '/traeger/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogSlugRoute: typeof BlogSlugRoute
  TeamVornameRoute: typeof TeamVornameRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ImpressumIndexRoute: typeof ImpressumIndexRoute
  KonzeptIndexRoute: typeof KonzeptIndexRoute
  TeamIndexRoute: typeof TeamIndexRoute
  TraegerIndexRoute: typeof TraegerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traeger/': {
      id: '/traeger/'
      path: '/traeger'
      fullPath: '/traeger/'
      preLoaderRoute: typeof TraegerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/': {
      id: '/team/'
      path: '/team'
      fullPath: '/team/'
      preLoaderRoute: typeof TeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konzept/': {
      id: '/konzept/'
      path: '/konzept'
      fullPath: '/konzept/'
      preLoaderRoute: typeof KonzeptIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum/': {
      id: '/impressum/'
      path: '/impressum'
      fullPath: '/impressum/'
      preLoaderRoute: typeof ImpressumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$vorname': {
      id: '/team/$vorname'
      path: '/team/$vorname'
      fullPath: '/team/$vorname'
      preLoaderRoute: typeof TeamVornameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogSlugRoute: BlogSlugRoute,
  TeamVornameRoute: TeamVornameRoute,
  BlogIndexRoute: BlogIndexRoute,
  ImpressumIndexRoute: ImpressumIndexRoute,
  KonzeptIndexRoute: KonzeptIndexRoute,
  TeamIndexRoute: TeamIndexRoute,
  TraegerIndexRoute: TraegerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
